development:
  port: 3000

  api:
    basePath: '/api/v1'

  database:
    host: 'ds149700.mlab.com'
    port: '49700'
    name: 'dev_groups_db'

    auth: true
    username: MONGO_USER
    password: MONGO_PASS

    collections:
      - name: groups
        schema: './groups-schema.json'

production:
  port: 80
  
  api:
    basePath: '/api/v1'

  database:
    host: 'ds151070.mlab.com'
    port: '51070'
    name: 'groups_db'

    auth: true
    username: MONGO_USER
    password: MONGO_PASS

    collections:
      - name: groups
        schema: './groups-schema.json'

test:
  port: 3000
  
  api:
    basePath: '/api/v1'

  database:
    host: 'ds149800.mlab.com'
    port: '49800'
    name: 'tests_groups_db'

    auth: true
    username: MONGO_USER
    password: MONGO_PASS

    collections:
      - name: groups
        schema: './groups-schema.json'